### ISSUE TITLE
Help , PNG 2 Bflim  It doesn't work.

### ISSUE THREAD

**Issue by fejich** [aboood40091/BFLIM-Extractor#1]
```
D:\Downloads\bflim\bflim_extract_v1.2>bflim_extract.exe "ti_npg001^l.bflim"
BFLIM Extractor v1.2
(C) 2016 AboodXD
Converting: ti_npg001^l.bflim

// ----- GX2Surface Info -----
  width     = 880
  height    = 100
  format    = GX2_SURFACE_FORMAT_TCS_R8_G8_B8_A8_UNORM
  imageSize = 401408
  swizzle   = 512, 0x200
  alignment = 2048
  pitch     = 896

Finished converting: ti_npg001^l.bflim

D:\Downloads\bflim\bflim_extract_v1.2>bflim_extract.exe "ti_npg001^l.png"
BFLIM Extractor v1.2
(C) 2016 AboodXD
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27
, in <module>

  File "bflim_extract.py", line 1048, in <module>
  File "bflim_extract.py", line 999, in main
IndexError: list index out of range
```

**Comment by fejich** [comment]
The bflim  from Wii Party U,i have no idea to convert it

**Comment by aboood40091** [comment]
This isn't how you use this program.

And I don't recommend using this program anyway, use this one:
https://github.com/aboood40091/BFLIM-Tool/releases
